### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by cassioalmeidas** [muhhanifra/Sign-Language-Recognition-modelling#1]
Could you please make your dataset available? And how was it collected?

**Comment by muhhanifra** [comment]
Unfortunately, I am unable to give you the dataset since it belongs to zapps.co.id. However, I am currently working on making my own dataset for a simple example of how the model might be implemented. But to give you some of the detail, the dataset is a set of video files where each video has T number of frames and T number of labels. A non zero label is assigned in some frame t  after a person has just done a specific "sign". To label/annotate these videos, you can use label-vid here:  https://github.com/muhhanifra/label-vid
Note that it still has a lot of bugs and I am still working my way to improve it.

**Comment by muhhanifra** [comment]
Unfortunately, I am unable to give you the dataset since it belongs to zapps.co.id. However, I am currently working on making my own dataset for a simple example of how the model might be implemented. But to give you some of the detail, the dataset is a set of video files where each video has T number of frames and T number of labels. A non zero label is assigned in some frame t  after a person has just done a specific "sign". To label/annotate these videos, you can use label-vid here:  https://github.com/muhhanifra/label-vid
Note that it still has a lot of bugs and I am still working my way to improve it.

**Comment by cassioalmeidas** [comment]
thank you very much
